# Greetings in different languages
# Source: https://www.rocketlanguages.com/blog/how-to-say-hello-in-the-worlds-most-spoken-languages
greetings:
  - 你好
  - Hola
  - Hello
  - नमस्ते
  - Oi
  - Olá
  - হ্যালো
  - Здравствуйте
  - 今日は
  - ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ।
  - Halo
  - 안녕하세요
  - 侬好
  - Hallo
  - Bonjour
  - నమస్కారం
  - नमस्कार
  - Merhaba
  - chào bạn
  - வணக்கம்
  - 你好
  - Ciao
  - Assalamualaikum
  - สวัสดี
  - Cześć
  - નમસ્તે
  - မဂႆလာပၝ
  - Вітаю
  - നമസ്തെ
  - 你好
  - ನಮಸ್ತೆ
  - ନମସ୍କାର
  - Salut
  - Salam
